### ISSUE TITLE
Feature Request: Multiple color values allowed per state

### ISSUE THREAD

**Issue by dwvisser** [PitchInteractiveInc/hexagon-cartograms#77]
I would like to be able to generate tilegrams visualizing state subpopulation breakdown, e.g.,

* racial/ethnic
* religious
* votes cast for various US presidential candidates, by state

I'm envisioning a tilegram with clearly marked state boundaries, allowing different colored hexagons within the state. I'd appreciate advice on how to accomplish this.

**Comment by jessihamel** [comment]
We haven't really thought about this as a use case. I think your best bet would be to load the svg and then color the hexagons using d3 or javascript. The [manual](https://github.com/PitchInteractiveInc/tilegrams/blob/master/MANUAL.md) has an example of loading a svg.

It's a bit trickier to accomplish this with the topojson as the states are drawn as a single path. Perhaps in the future we could think about exporting a topojson file that has separate features for each hexagon rather than each state.
